name: anipi
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">3.0.0"

dependencies:
  dart_frog: ^0.3.5
  dio: 
  html:
  chitose: 
  encrypt:
  compute:
  petitparser: 
  http: ^0.13.5
  js_unpack:

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  lints:
