name: anipi
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">3.0.0"

dependencies:

  dart_frog: 
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog
  dio: 
  html:
  chitose: 
  encrypt:
  compute:
  string_similarity: 

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  lints:
