name: hanime
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dio: ^5.0.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  lints:
